# Listas

Las listas son variables que pueden guardar mas de un elemento. 

Para guardar mas de un elemento, se usan los corchetes [ ]

In [ ]:
numero = 4 # la variable número solo almacena el elemento 4
print(numero)

4

La variable **listas**, almacena varios tipos de datos, con solo usar los corchetes y separar los elementos con comas ','.

en el ejemplo se observa que almacena tipos de datos como numéricos, de texto, decimales y booleanos.

In [ ]:
listas = [5, 'cinco', 5.5, True]  # la variable listas puede almacenar varios tipos de datos
print(listas)

[5, 'cinco', 5.5, True]

Crear una lista de los planetas del sistema solar: Mercurio, Venus, Tierra, Marte, Júpiter, Saturno, Urano y Neptuno

In [1]:
planetas = ['Mercurio','Venus','Tierra','Marte','Júpiter','Saturno','Urano','Neptuno']
print(planetas)

['Mercurio', 'Venus', 'Tierra', 'Marte', 'Júpiter', 'Saturno', 'Urano', 'Neptuno']

Imprimir la lista de planetas de forma inversa.

In [2]:
print(planetas[::-1])

['Neptuno', 'Urano', 'Saturno', 'Júpiter', 'Marte', 'Tierra', 'Venus', 'Mercurio']